create database BAMAZON_DB;
use BAMAZON_DB;

create table PRODUCTS(
    ITEM_ID INTEGER NOT NULL AUTO_INCREMENT,
    PRODUCT_NAME VARCHAR(50) NOT NULL,
    DEPARTMENT_NAME VARCHAR(50),
    PRICE INTEGER,
    STOCK_QUANTITY INTEGER,
    PRIMARY KEY (ITEM_ID)
);